# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5a1e3268-ab96-445c-add0-adbd467fa0cf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5a1e3268-ab96-445c-add0-adbd467fa0cf".device = "/dev/disk/by-uuid/5a1e3268-ab96-445c-add0-adbd467fa0cf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3247-77A8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ebcbe638-86cd-4b00-a52d-7db57af258dd"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
