# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1d49a675-46ad-4de9-a42d-702fcbf9977a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1d49a675-46ad-4de9-a42d-702fcbf9977a".device = "/dev/disk/by-uuid/1d49a675-46ad-4de9-a42d-702fcbf9977a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5E38-519B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3bb8ecd6-e3d4-46d2-b2e8-cf132005ad10"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
